### ISSUE TITLE
Pancit Bihon Recipe!!! (Filipino Food) 😋

### ISSUE THREAD

**Issue by Kuugang** [JunSayke/JunSayke#1]
![image](https://github.com/user-attachments/assets/73eb3d2e-ad95-4ff3-97ea-cfc770c0eb12)

Pancit Bihon is a Filipino stir fried rice noodle dish that contains a variety of meats and vegetables.

Ingredients

• Oil (2-3tsp)

• Onion (1/2 large, julienne cut)

• Garlic (4 cloves, minced)

• Chicken Thigh (1/2lb cut into about 1 1/2 in. strips)

• Shrimp (1/2lb, peeled)

• Pepper (1/4 tsp)

• Carrot (1 cup, julienne cut)

• Celery (1 cup, diced)

• Cabbage (1/4 head, cut into strips)

• Soy Sauce (1/4 cup)

• Chicken Stock (2 cups, unsalted)

• Bihon Rice Noodles (8oz)

Steps

First, in a large wok, sauté 1/2 a large julienne cut onion in 2-3 tsp of oil until it’s translucent.

Next, add 4 cloves of minced garlic and sauté them until they’re fragrant.

Then add a 1/2 a pound of chicken thighs, cut into 1 1/2 inch strips, and cook them until they’re about 80-90% cooked.

Afterwards, add a 1/2 a pound of peeled shrimp and cook them through.

Next added 1 cup of julienne cut carrots and cook for a minute or so. Make sure they do not become soggy and over cooked.

Then throw in 1 cup of sliced celery and cook for about a minute.

Afterwards, add 1/4 of a head of cabbage sliced into strips.

Then, season the vegetable and meat stir fry with 1/4 tsp of pepper, 1/4 cup of soy sauce and 1 cup of unsalted chicken stock.

Once everything is mixed and the flavors have infused into the stir fry, transfer the vegetables and meat to a different bowl leaving only the chicken stock and soy sauce in the wok.

Next add 1 more cup of unsalted chicken stock to the wok.

Then put 8oz of bihon rice noodles into the wok and allow it to soak up all of the stock and soy sauce.

After the noodles soften and all of the stock is soaked up, add the vegetables and meat back in to the wok.

Mix everything together thoroughly. We recommend using 2 serving utensils to make it easier to mix the ingredients. And you’re done!

Pro Tips

• Squeeze calamansi or lemon juice on your pancit before eating!

**Comment by avrilnigelchua0412** [comment]
![megumin-eating-v0-3w3nno8zx15d1](https://github.com/user-attachments/assets/a1c054ff-dc56-4985-8a5c-bdb4aaa1130c)

Yummy
OMG🌝🌚 I wanna schlurp that! 😮😲 What’s that mean you say? 🤔🤔❓ Well I wanna: Slurp that, sloppily sucking on it as the juices run down my chin. 🤤🤤 I wanna schlorp it all up, every last drop until all that remains is my wet saliva. 😋😋Just really get in there, you know? 😎😎

**Comment by JunSayke** [comment]
Very nice but its a no for me charrot

**Comment by Kuugang** [comment]
okay

**Comment by avrilnigelchua0412** [comment]
https://www.youtube.com/watch?v=_k-8ta5SgKU&pp=ygUIcGFraXNhYmk%3D

**Comment by Dioooooooooooooooo** [comment]
soyjack
![image](https://github.com/user-attachments/assets/b97ad0e0-043c-408e-9d23-7a4dad992a57)
